# Generated by Django 3.2.8 on 2021-12-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time'], 'verbose_name': 'comment', 'verbose_name_plural': 'comment'},
        ),
    ]
